name = "ConditionalDensityLayers"
uuid = "e5962c11-610b-40b9-b00c-310314db9149"
authors = ["aronStalmarck <aron.stalmarck@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
